name = "cajun-kitchen"
account_id = "d6ec056b27a57bcf807a46b2e3379d60"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "KV"
id = "e61605d144ac4348a72b7e85afc6c185"
